services:
    chatbot.message:
        class: ChatbotBundle\Services\ChatMessageService
    chatbot.server:
        class: ChatbotBundle\Services\ChatServerService
        arguments: ["@chatbot.message"]
#        arguments: [@service_id, "plain_value", %parameter%]
