System.config({
  "transpiler": "traceur",
  "paths": {
    "*": "*.js",
    "github:*": "/jspm_packages/github/*.js",
    "npm:*": "/jspm_packages/npm/*.js"
  },
  "bundles": {
    "aurelia": [
      "npm:core-js@0.9.18/modules/$.fw",
      "npm:core-js@0.9.18/modules/$.dom-create",
      "npm:core-js@0.9.18/modules/$.shared",
      "npm:core-js@0.9.18/modules/$.uid",
      "npm:core-js@0.9.18/modules/$.redef",
      "npm:core-js@0.9.18/modules/$.invoke",
      "npm:core-js@0.9.18/modules/$.assert",
      "npm:core-js@0.9.18/modules/$.array-includes",
      "npm:core-js@0.9.18/modules/$.replacer",
      "npm:core-js@0.9.18/modules/$.throws",
      "npm:core-js@0.9.18/modules/$.keyof",
      "npm:core-js@0.9.18/modules/$.enum-keys",
      "npm:core-js@0.9.18/modules/$.get-names",
      "npm:core-js@0.9.18/modules/$.assign",
      "npm:core-js@0.9.18/modules/$.same",
      "npm:core-js@0.9.18/modules/$.set-proto",
      "npm:core-js@0.9.18/modules/es6.object.to-string",
      "npm:core-js@0.9.18/modules/es6.object.statics-accept-primitives",
      "npm:core-js@0.9.18/modules/es6.function.name",
      "npm:core-js@0.9.18/modules/es6.function.has-instance",
      "npm:core-js@0.9.18/modules/es6.number.constructor",
      "npm:core-js@0.9.18/modules/es6.number.statics",
      "npm:core-js@0.9.18/modules/es6.math",
      "npm:core-js@0.9.18/modules/es6.string.from-code-point",
      "npm:core-js@0.9.18/modules/es6.string.raw",
      "npm:core-js@0.9.18/modules/$.string-at",
      "npm:core-js@0.9.18/modules/$.iter",
      "npm:core-js@0.9.18/modules/$.iter-define",
      "npm:core-js@0.9.18/modules/es6.string.code-point-at",
      "npm:core-js@0.9.18/modules/es6.string.ends-with",
      "npm:core-js@0.9.18/modules/es6.string.includes",
      "npm:core-js@0.9.18/modules/$.string-repeat",
      "npm:core-js@0.9.18/modules/es6.string.starts-with",
      "npm:core-js@0.9.18/modules/$.iter-call",
      "npm:core-js@0.9.18/modules/$.iter-detect",
      "npm:core-js@0.9.18/modules/es6.array.of",
      "npm:core-js@0.9.18/modules/$.unscope",
      "npm:core-js@0.9.18/modules/$.species",
      "npm:core-js@0.9.18/modules/es6.array.copy-within",
      "npm:core-js@0.9.18/modules/es6.array.fill",
      "npm:core-js@0.9.18/modules/es6.array.find",
      "npm:core-js@0.9.18/modules/es6.array.find-index",
      "npm:core-js@0.9.18/modules/es6.regexp",
      "npm:core-js@0.9.18/modules/$.for-of",
      "npm:process@0.10.1/browser",
      "npm:core-js@0.9.18/modules/$.mix",
      "npm:core-js@0.9.18/modules/$.collection-strong",
      "npm:core-js@0.9.18/modules/$.collection",
      "npm:core-js@0.9.18/modules/es6.set",
      "npm:core-js@0.9.18/modules/$.collection-weak",
      "npm:core-js@0.9.18/modules/es6.weak-set",
      "npm:core-js@0.9.18/modules/$.own-keys",
      "npm:core-js@0.9.18/modules/es7.array.includes",
      "npm:core-js@0.9.18/modules/es7.string.at",
      "npm:core-js@0.9.18/modules/$.string-pad",
      "npm:core-js@0.9.18/modules/es7.string.rpad",
      "npm:core-js@0.9.18/modules/es7.regexp.escape",
      "npm:core-js@0.9.18/modules/es7.object.get-own-property-descriptors",
      "npm:core-js@0.9.18/modules/es7.object.to-array",
      "npm:core-js@0.9.18/modules/$.collection-to-json",
      "npm:core-js@0.9.18/modules/es7.set.to-json",
      "npm:core-js@0.9.18/modules/js.array.statics",
      "npm:core-js@0.9.18/modules/$.partial",
      "npm:core-js@0.9.18/modules/web.immediate",
      "npm:core-js@0.9.18/modules/web.dom.iterable",
      "npm:core-js@0.9.18/modules/core.dict",
      "npm:core-js@0.9.18/modules/core.iter-helpers",
      "npm:core-js@0.9.18/modules/core.$for",
      "npm:core-js@0.9.18/modules/core.delay",
      "npm:core-js@0.9.18/modules/core.function.part",
      "npm:core-js@0.9.18/modules/core.object",
      "npm:core-js@0.9.18/modules/core.array.turn",
      "npm:core-js@0.9.18/modules/core.number.iterator",
      "npm:core-js@0.9.18/modules/core.number.math",
      "npm:core-js@0.9.18/modules/core.string.escape-html",
      "npm:core-js@0.9.18/modules/core.date",
      "npm:core-js@0.9.18/modules/core.global",
      "npm:core-js@0.9.18/modules/core.log",
      "github:aurelia/metadata@0.6.0/reflect-metadata",
      "github:aurelia/metadata@0.6.0/decorator-applicator",
      "github:aurelia/path@0.7.0/index",
      "github:aurelia/loader@0.7.0/loader",
      "npm:core-js@0.9.18/modules/$",
      "npm:core-js@0.9.18/modules/$.wks",
      "npm:core-js@0.9.18/modules/$.def",
      "npm:core-js@0.9.18/modules/$.ctx",
      "npm:core-js@0.9.18/modules/es6.symbol",
      "npm:core-js@0.9.18/modules/es6.object.assign",
      "npm:core-js@0.9.18/modules/es6.object.is",
      "npm:core-js@0.9.18/modules/es6.object.set-prototype-of",
      "npm:core-js@0.9.18/modules/es6.string.iterator",
      "npm:core-js@0.9.18/modules/es6.string.repeat",
      "npm:core-js@0.9.18/modules/es6.array.from",
      "npm:core-js@0.9.18/modules/es6.array.iterator",
      "npm:core-js@0.9.18/modules/es6.array.species",
      "npm:process@0.10.1",
      "npm:core-js@0.9.18/modules/es6.map",
      "npm:core-js@0.9.18/modules/es6.weak-map",
      "npm:core-js@0.9.18/modules/es6.reflect",
      "npm:core-js@0.9.18/modules/es7.string.lpad",
      "npm:core-js@0.9.18/modules/es7.map.to-json",
      "npm:core-js@0.9.18/modules/web.timers",
      "github:aurelia/metadata@0.6.0/metadata",
      "github:aurelia/metadata@0.6.0/decorators",
      "github:aurelia/path@0.7.0",
      "npm:core-js@0.9.18/modules/$.cof",
      "npm:core-js@0.9.18/modules/$.array-methods",
      "github:jspm/nodelibs-process@0.1.1/index",
      "github:aurelia/loader@0.7.0/template-registry-entry",
      "npm:core-js@0.9.18/modules/es5",
      "github:jspm/nodelibs-process@0.1.1",
      "github:aurelia/loader@0.7.0/index",
      "npm:core-js@0.9.18/modules/$.task",
      "github:aurelia/loader@0.7.0",
      "npm:core-js@0.9.18/modules/es6.promise",
      "npm:core-js@0.9.18/shim",
      "npm:core-js@0.9.18/index",
      "npm:core-js@0.9.18",
      "github:aurelia/metadata@0.6.0/origin",
      "github:aurelia/metadata@0.6.0/index",
      "github:aurelia/metadata@0.6.0",
      "github:aurelia/loader-default@0.8.0/index",
      "github:aurelia/loader-default@0.8.0",
      "github:aurelia/binding@0.7.3/value-converter",
      "github:aurelia/binding@0.7.3/class-list",
      "github:aurelia/binding@0.7.3/event-manager",
      "github:aurelia/task-queue@0.5.0/index",
      "github:aurelia/binding@0.7.3/environment",
      "github:aurelia/binding@0.7.3/array-change-records",
      "github:aurelia/binding@0.7.3/map-change-records",
      "github:aurelia/binding@0.7.3/map-observation",
      "github:aurelia/binding@0.7.3/dirty-checking",
      "github:aurelia/binding@0.7.3/property-observation",
      "github:aurelia/binding@0.7.3/element-observation",
      "github:aurelia/binding@0.7.3/class-observer",
      "github:aurelia/dependency-injection@0.8.1/metadata",
      "github:aurelia/logging@0.5.0/index",
      "github:aurelia/binding@0.7.3/computed-observation",
      "github:aurelia/binding@0.7.3/svg",
      "github:aurelia/binding@0.7.3/binding-modes",
      "github:aurelia/binding@0.7.3/lexer",
      "github:aurelia/binding@0.7.3/path-observer",
      "github:aurelia/binding@0.7.3/composite-observer",
      "github:aurelia/binding@0.7.3/access-keyed-observer",
      "github:aurelia/binding@0.7.3/binding-expression",
      "github:aurelia/binding@0.7.3/listener-expression",
      "github:aurelia/binding@0.7.3/name-expression",
      "github:aurelia/binding@0.7.3/call-expression",
      "github:aurelia/task-queue@0.5.0",
      "github:aurelia/binding@0.7.3/collection-observation",
      "github:aurelia/logging@0.5.0",
      "github:aurelia/binding@0.7.3/ast",
      "github:aurelia/binding@0.7.3/array-observation",
      "github:aurelia/dependency-injection@0.8.1/container",
      "github:aurelia/binding@0.7.3/parser",
      "github:aurelia/dependency-injection@0.8.1/index",
      "github:aurelia/dependency-injection@0.8.1",
      "github:aurelia/binding@0.7.3/observer-locator",
      "github:aurelia/binding@0.7.3/index",
      "github:aurelia/binding@0.7.3",
      "github:aurelia/templating@0.12.1/resource-registry",
      "github:aurelia/templating@0.12.1/view",
      "github:aurelia/templating@0.12.1/content-selector",
      "github:aurelia/templating@0.12.1/animator",
      "github:aurelia/templating@0.12.1/util",
      "github:aurelia/templating@0.12.1/binding-language",
      "github:aurelia/templating@0.12.1/module-analyzer",
      "github:aurelia/templating@0.12.1/bindable-property",
      "github:aurelia/templating@0.12.1/behavior-instance",
      "github:aurelia/templating@0.12.1/children",
      "github:aurelia/templating@0.12.1/element-config",
      "github:aurelia/templating@0.12.1/composition-engine",
      "github:aurelia/templating@0.12.1/decorators",
      "github:aurelia/templating-binding@0.12.0/syntax-interpreter",
      "github:aurelia/templating@0.12.1/view-slot",
      "github:aurelia/templating-binding@0.12.0/binding-language",
      "github:aurelia/templating@0.12.1/view-strategy",
      "github:aurelia/templating@0.12.1/view-factory",
      "github:aurelia/templating@0.12.1/view-compiler",
      "github:aurelia/templating@0.12.1/view-engine",
      "github:aurelia/templating@0.12.1/html-behavior",
      "github:aurelia/templating@0.12.1/index",
      "github:aurelia/templating@0.12.1",
      "github:aurelia/templating-binding@0.12.0/index",
      "github:aurelia/templating-binding@0.12.0",
      "github:aurelia/templating-resources@0.12.1/if",
      "github:aurelia/templating-resources@0.12.1/with",
      "github:aurelia/templating-resources@0.12.1/repeat",
      "github:aurelia/templating-resources@0.12.1/show",
      "github:aurelia/templating-resources@0.12.1/global-behavior",
      "github:aurelia/templating-resources@0.12.1/sanitize-html",
      "github:aurelia/templating-resources@0.12.1/replaceable",
      "github:aurelia/templating-resources@0.12.1/focus",
      "github:aurelia/templating-resources@0.12.1/compose",
      "github:aurelia/templating-resources@0.12.1/index",
      "github:aurelia/templating-resources@0.12.1",
      "github:aurelia/route-recognizer@0.5.0/state",
      "github:aurelia/route-recognizer@0.5.0/segments",
      "github:aurelia/router@0.9.0/navigation-commands",
      "github:aurelia/router@0.9.0/util",
      "github:aurelia/router@0.9.0/navigation-instruction",
      "github:aurelia/router@0.9.0/nav-model",
      "github:aurelia/history@0.5.0/index",
      "github:aurelia/router@0.9.0/pipeline",
      "github:aurelia/router@0.9.0/route-loading",
      "github:aurelia/router@0.9.0/activation",
      "github:aurelia/event-aggregator@0.5.0/index",
      "github:aurelia/templating-router@0.13.0/router-view",
      "github:aurelia/templating-router@0.13.0/route-href",
      "github:aurelia/route-recognizer@0.5.0/index",
      "github:aurelia/router@0.9.0/navigation-plan",
      "github:aurelia/history@0.5.0",
      "github:aurelia/router@0.9.0/pipeline-provider",
      "github:aurelia/event-aggregator@0.5.0",
      "github:aurelia/route-recognizer@0.5.0",
      "github:aurelia/router@0.9.0/navigation-context",
      "github:aurelia/router@0.9.0/app-router",
      "github:aurelia/router@0.9.0/route-filters",
      "github:aurelia/router@0.9.0/router-configuration",
      "github:aurelia/router@0.9.0/router",
      "github:aurelia/templating-router@0.13.0/route-loader",
      "github:aurelia/router@0.9.0/index",
      "github:aurelia/router@0.9.0",
      "github:aurelia/templating-router@0.13.0/index",
      "github:aurelia/templating-router@0.13.0",
      "github:aurelia/history-browser@0.5.0/index",
      "github:aurelia/history-browser@0.5.0",
      "github:aurelia/framework@0.12.0/plugins",
      "github:aurelia/framework@0.12.0/aurelia",
      "github:aurelia/framework@0.12.0/index",
      "github:aurelia/framework@0.12.0",
      "github:aurelia/http-client@0.9.1/headers",
      "github:aurelia/http-client@0.9.1/http-response-message",
      "github:aurelia/http-client@0.9.1/transformers",
      "github:aurelia/http-client@0.9.1/jsonp-request-message",
      "github:aurelia/http-client@0.9.1/request-message-processor",
      "github:aurelia/http-client@0.9.1/http-request-message",
      "github:aurelia/http-client@0.9.1/request-builder",
      "github:aurelia/http-client@0.9.1/http-client",
      "github:aurelia/http-client@0.9.1/index",
      "github:aurelia/http-client@0.9.1",
      "github:aurelia/logging-console@0.5.0/index",
      "github:aurelia/logging-console@0.5.0",
      "github:aurelia/bootstrapper@0.13.1/index",
      "github:aurelia/bootstrapper@0.13.1"
    ]
  }
});

System.config({
  "map": {
    "aurelia-bootstrapper": "github:aurelia/bootstrapper@0.13.1",
    "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.8.1",
    "aurelia-framework": "github:aurelia/framework@0.12.0",
    "aurelia-http-client": "github:aurelia/http-client@0.9.1",
    "aurelia-router": "github:aurelia/router@0.9.0",
    "bootstrap": "github:twbs/bootstrap@3.3.5",
    "css": "github:systemjs/plugin-css@0.1.13",
    "font-awesome": "npm:font-awesome@4.3.0",
    "foundation": "github:zurb/bower-foundation@5.5.2",
    "traceur": "github:jmcriffey/bower-traceur@0.0.88",
    "traceur-runtime": "github:jmcriffey/bower-traceur-runtime@0.0.88",
    "github:aurelia/binding@0.7.3": {
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.8.1",
      "aurelia-metadata": "github:aurelia/metadata@0.6.0",
      "aurelia-task-queue": "github:aurelia/task-queue@0.5.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/bootstrapper@0.13.1": {
      "aurelia-event-aggregator": "github:aurelia/event-aggregator@0.5.0",
      "aurelia-framework": "github:aurelia/framework@0.12.0",
      "aurelia-history": "github:aurelia/history@0.5.0",
      "aurelia-history-browser": "github:aurelia/history-browser@0.5.0",
      "aurelia-loader-default": "github:aurelia/loader-default@0.8.0",
      "aurelia-logging-console": "github:aurelia/logging-console@0.5.0",
      "aurelia-router": "github:aurelia/router@0.9.0",
      "aurelia-templating": "github:aurelia/templating@0.12.1",
      "aurelia-templating-binding": "github:aurelia/templating-binding@0.12.0",
      "aurelia-templating-resources": "github:aurelia/templating-resources@0.12.1",
      "aurelia-templating-router": "github:aurelia/templating-router@0.13.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/dependency-injection@0.8.1": {
      "aurelia-logging": "github:aurelia/logging@0.5.0",
      "aurelia-metadata": "github:aurelia/metadata@0.6.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/event-aggregator@0.5.0": {
      "aurelia-logging": "github:aurelia/logging@0.5.0"
    },
    "github:aurelia/framework@0.12.0": {
      "aurelia-binding": "github:aurelia/binding@0.7.3",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.8.1",
      "aurelia-loader": "github:aurelia/loader@0.7.0",
      "aurelia-logging": "github:aurelia/logging@0.5.0",
      "aurelia-metadata": "github:aurelia/metadata@0.6.0",
      "aurelia-path": "github:aurelia/path@0.7.0",
      "aurelia-task-queue": "github:aurelia/task-queue@0.5.0",
      "aurelia-templating": "github:aurelia/templating@0.12.1",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/history-browser@0.5.0": {
      "aurelia-history": "github:aurelia/history@0.5.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/http-client@0.9.1": {
      "aurelia-path": "github:aurelia/path@0.7.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/loader-default@0.8.0": {
      "aurelia-loader": "github:aurelia/loader@0.7.0",
      "aurelia-metadata": "github:aurelia/metadata@0.6.0"
    },
    "github:aurelia/loader@0.7.0": {
      "aurelia-html-template-element": "github:aurelia/html-template-element@0.2.0",
      "aurelia-path": "github:aurelia/path@0.7.0",
      "core-js": "npm:core-js@0.9.18",
      "webcomponentsjs": "github:webcomponents/webcomponentsjs@0.6.3"
    },
    "github:aurelia/metadata@0.6.0": {
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/route-recognizer@0.5.0": {
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/router@0.9.0": {
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.8.1",
      "aurelia-event-aggregator": "github:aurelia/event-aggregator@0.5.0",
      "aurelia-history": "github:aurelia/history@0.5.0",
      "aurelia-path": "github:aurelia/path@0.7.0",
      "aurelia-route-recognizer": "github:aurelia/route-recognizer@0.5.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/templating-binding@0.12.0": {
      "aurelia-binding": "github:aurelia/binding@0.7.3",
      "aurelia-logging": "github:aurelia/logging@0.5.0",
      "aurelia-templating": "github:aurelia/templating@0.12.1"
    },
    "github:aurelia/templating-resources@0.12.1": {
      "aurelia-binding": "github:aurelia/binding@0.7.3",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.8.1",
      "aurelia-logging": "github:aurelia/logging@0.5.0",
      "aurelia-task-queue": "github:aurelia/task-queue@0.5.0",
      "aurelia-templating": "github:aurelia/templating@0.12.1",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/templating-router@0.13.0": {
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.8.1",
      "aurelia-metadata": "github:aurelia/metadata@0.6.0",
      "aurelia-path": "github:aurelia/path@0.7.0",
      "aurelia-router": "github:aurelia/router@0.9.0",
      "aurelia-templating": "github:aurelia/templating@0.12.1"
    },
    "github:aurelia/templating@0.12.1": {
      "aurelia-binding": "github:aurelia/binding@0.7.3",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.8.1",
      "aurelia-html-template-element": "github:aurelia/html-template-element@0.2.0",
      "aurelia-loader": "github:aurelia/loader@0.7.0",
      "aurelia-logging": "github:aurelia/logging@0.5.0",
      "aurelia-metadata": "github:aurelia/metadata@0.6.0",
      "aurelia-path": "github:aurelia/path@0.7.0",
      "aurelia-task-queue": "github:aurelia/task-queue@0.5.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:jspm/nodelibs-process@0.1.1": {
      "process": "npm:process@0.10.1"
    },
    "github:twbs/bootstrap@3.3.5": {
      "jquery": "github:components/jquery@2.1.4"
    },
    "github:zurb/bower-foundation@5.5.2": {
      "jquery": "github:components/jquery@2.1.4"
    },
    "npm:core-js@0.9.18": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:font-awesome@4.3.0": {
      "css": "github:systemjs/plugin-css@0.1.13"
    }
  }
});

